version: '3.8'

services:
  ml_service:
    build: ./ml_service
    ports:
      - "5000:5000"
    restart: always

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - ml_service
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

